### ISSUE TITLE
`TypeContext#typeParameters` does not recursively look up parameterized types

### ISSUE THREAD

**Issue by pumbas600** [GuusLieben/Hartshorn#636]
### Version

4.2.4

### Problem/Opportunity

When trying to get the generic type of a `ParameterContext`, it uses the following to create the `TypeContext`:
```java
    protected static <T> TypeContext<T> of(final ParameterizedType type) {
        TypeContext<T> context = of((Class)type.getRawType());
        context.typeParameters = context.contextsFromParameterizedType(type);
        return context;
    }
```

Unfortunately, when it tries to retrieve the contexts from the parameterized type, it filters to check the type is an instance of `Class` or `WildcardType`: https://github.com/GuusLieben/Hartshorn/blob/a4824845589a94345ecbd45cd6af977f32bd18c5/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java#L325 However, if the type was generic (And therefore an instance of `ParametizedType` both these conditions fail, causing it to be excluded:

![image](https://user-images.githubusercontent.com/38820160/147713565-8d70ae93-21db-4970-a16d-96f4d500e3ab.png)
![image](https://user-images.githubusercontent.com/38820160/147713571-7098f603-cbee-41db-9582-563c7c5366c2.png)

### The Tests

```java
    @Test
    public void genericTypeTests() {
        ParameterContext<?> parameter = TypeContext.of(this).method("genericTestMethod", List.class)
                .get()
                .parameters()
                .get(0);

        TypeContext<?> genericType = parameter.genericType();

        Assertions.assertTrue(genericType.is(List.class));
        Assertions.assertEquals(1, genericType.typeParameters().size());

        genericType = genericType.typeParameters().get(0);
        Assertions.assertTrue(genericType.is(List.class));
        Assertions.assertEquals(1, genericType.typeParameters().size());

        genericType = genericType.typeParameters().get(0);
        Assertions.assertTrue(genericType.is(String.class));
        Assertions.assertEquals(0, genericType.typeParameters().size());
    }

    public void genericTestMethod(List<List<String>> nestedGeneric) { }
```

The test fails on the first `assertEquals`

### Proposed solution

Add an additional path to allow for the parsing of `ParameterizedTypes`

**Comment by GuusLieben** [comment]
To mirror our conversation from earlier today, this issue can be exemplified by the following code snippet:
```java
void handleNested(List<Set<String>> nested);
void handleDirect(List<String> direct);
```
In this example, getting `List<Set<String>> nested` as a type, will result in a `TypeContext<List>` without type parameters. This is caused by the `Set` being a `ParameterizedType`, which is not currently included in the type parameter lookup.  
Getting `List<String>` however, will result in a `TypeContext<List>` with `String` being the first and only type parameter, as it is a `Class` type.  

As @pumbas600 suggested, this should be resolveable by adding additional support for `ParameterizedType` at the line below, and adding a final condition to the mapping to direct parameterized types to the correct `TypeContext` builder.
https://github.com/GuusLieben/Hartshorn/blob/a4824845589a94345ecbd45cd6af977f32bd18c5/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java#L325

The current mapping conditions:
https://github.com/GuusLieben/Hartshorn/blob/a4824845589a94345ecbd45cd6af977f32bd18c5/hartshorn-core/src/main/java/org/dockbox/hartshorn/core/context/element/TypeContext.java#L327-L329
